### ISSUE TITLE
UX: Bigger multiple choice buttons

### ISSUE THREAD

**Issue by mmenavas** [PhoenixJSMeetup/mathbeast#10]
Multiple choice buttons need to be bigger and closer to each other, speacially on large screens.

**Comment by Oh-KPond** [comment]
I'm thinking that maybe we can fix those buttons by doing something like this:  

http://stackoverflow.com/questions/13112200/resizing-buttons-in-twitter-bootstrap

I'm trying it out now.

**Comment by Oh-KPond** [comment]
It doesn't seem to have done anything. I'll keep trying.

**Comment by mmenavas** [comment]
In the future please edit the most appropriate file from the css directory to override Bootstrap styles. Most of the time you'll be working with styles.css

I'm closing this issue as the css changes you made in PR #12 were implemented in the mvp4 branch.
