### ISSUE TITLE
UX: Remove focus from answer button

### ISSUE THREAD

**Issue by mmenavas** [PhoenixJSMeetup/mathbeast#13]
After clicking on an answer button, the focus stays on that button. The focus should be cleared after a question is answered.

**Comment by strangelyblue** [comment]
I found that doing something like this in CSS works:
.answers button:focus{
    background:white;
    outline:0;
}

Is it okay to just override the bootstrap styling like that?
By the way this is Kelly...

**Comment by mmenavas** [comment]
I'm closing this issue because @strangelyblue fixed this issue in PR #14
