### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by mmenavas** [PhoenixJSMeetup/mathbeast#17]
Provide instructions on how developers can contribute to MathBeast. Include the following:
- What libraries does MathBeast use?
- What code conventions should be used for html, css and javascript?
- Explain code review workflow
- How does CSS code get compiled?
- How to set up gulp?

Additionally, provide link to CONTRIBUTING.md in README.md

**Comment by fjbarrett** [comment]
@mmenavas Your instructions within the CONTRIBUTING.md are clear and well-laid out. I got up and running in a couple minutes!
